/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as access from "./access";
export type { access };
import type * as interfaces from "./interfaces";
export type { interfaces };
import type * as libs from "./libs";
export type { libs };
import type * as mock from "./mock";
export type { mock };
export type { Dramas } from "./Dramas";
