/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as access from "./access";
export * as interfaces from "./interfaces";
export * as libs from "./libs";
export * as mock from "./mock";
export { Dramas__factory } from "./Dramas__factory";
