/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  ICommonError,
  ICommonErrorInterface,
} from "../../../contracts/interfaces/ICommonError";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "current",
        type: "address",
      },
    ],
    name: "CannotUseCurrentAddress",
    type: "error",
  },
  {
    inputs: [
      {
        internalType: "bool",
        name: "current",
        type: "bool",
      },
    ],
    name: "CannotUseCurrentState",
    type: "error",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "invalid",
        type: "address",
      },
    ],
    name: "InvalidAddress",
    type: "error",
  },
] as const;

export class ICommonError__factory {
  static readonly abi = _abi;
  static createInterface(): ICommonErrorInterface {
    return new Interface(_abi) as ICommonErrorInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): ICommonError {
    return new Contract(address, _abi, runner) as unknown as ICommonError;
  }
}
